import requests
from bs4 import BeautifulSoup
import csv

'''
利用店舗一覧 | 奈良Go To EATキャンペーン  プレミアムお食事券 https://premium-gift.jp/nara-eat/use_store
店舗の一覧をCSVにする
'''
with open('gotoeatnarastorelist.csv', 'w') as f:
    writer = csv.writer(f)
    writer.writerow([' 店舗名','店舗住所','カテゴリー','電話番号','URL'])
    for page in range(1,64):
        url= 'https://premium-gift.jp/nara-eat/use_store?events=page&id={page}&store=&addr=&industry='.format(page=page)
        print(url)
        response = requests.get(url)

        soup = BeautifulSoup(response.text,"html.parser")

        storeitem =soup.findAll(class_="store-card__item")
        for item in storeitem:
            storename=item.find(class_="store-card__title").text
            storecategory=item.find(class_="store-card__tag").text


            storeaddress=item.find(class_="store-card__table").findAll("td")[0].text #Address
            storetel=item.find(class_="store-card__table").findAll("td")[1].text #tel
            storeurl=item.find(class_="store-card__table").findAll("td")[2].text.strip() #URL
            writer.writerow([storename,storeaddress,storecategory,storetel,storeurl])
'''        
Googleスプレッドシートの住所一覧をインポートし営業用のマイマップを自動生成する方法
https://tonari-it.com/google-mymap-autogenerated/
PythonでHTMLを解析してデータ収集してみる？ スクレイピングが最初からわかる『Python 2年生』：CodeZine（コードジン）
https://codezine.jp/article/detail/12230
HTTPのPOST/GETリクエストをする | Python Snippets
https://python.civic-apps.com/http-request-post-get/
PythonでCSVファイルを読み込み・書き込み（入力・出力） | note.nkmk.me
https://note.nkmk.me/python-csv-reader-writer/
CSVファイルをインポートする【Googleスプレッドシート】 | G Suite ガイド
https://gsuiteguide.jp/sheets/guide-import_csv/

'''